In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
a.size

5

In [4]:
a[-1]

5

In [99]:
#np.random.seed(10)
nd = np.random.random([1,10])
nd

array([[0.91130022, 0.40087668, 0.2868907 , 0.84304489, 0.61704455,
        0.14059873, 0.22875561, 0.84149797, 0.84435847, 0.22014599]])

In [128]:
np.random.seed(2019)
nd1 = np.random.randint(1,10,[2,3])
nd1
nd2 = np.random.randn(2,3)
nd2

array([[-0.36186537,  0.68560883,  0.57376143],
       [ 0.28772767, -0.23563426,  0.95349024]])

In [139]:
b=np.arange(16).reshape((2,2,4))
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [147]:
b[1][1]
#b[0,1,3:]


array([12, 13, 14, 15])